# TCL File Generated by Component Editor 20.1
# Sat Oct 30 19:06:02 IDT 2021
# DO NOT MODIFY


# 
# AvalonMaster_AltInit "AvalonMaster_AltInit" v1.0
#  2021.10.30.19:06:02
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module AvalonMaster_AltInit
# 
set_module_property DESCRIPTION ""
set_module_property NAME AvalonMaster_AltInit
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "CusP components"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME AvalonMaster_AltInit
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL AvalonMaster_AltInit
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file AltInitConstantPKG.vhd VHDL PATH AltInitConstantPKG.vhd
add_fileset_file AvalonMaster_AltInit.vhd VHDL PATH AvalonMaster_AltInit.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point c0_reset
# 
add_interface c0_reset reset end
set_interface_property c0_reset associatedClock c0
set_interface_property c0_reset synchronousEdges DEASSERT
set_interface_property c0_reset ENABLED true
set_interface_property c0_reset EXPORT_OF ""
set_interface_property c0_reset PORT_NAME_MAP ""
set_interface_property c0_reset CMSIS_SVD_VARIABLES ""
set_interface_property c0_reset SVD_ADDRESS_GROUP ""

add_interface_port c0_reset csi_c0_reset_n reset_n Input 1


# 
# connection point c0
# 
add_interface c0 clock end
set_interface_property c0 clockRate 0
set_interface_property c0 ENABLED true
set_interface_property c0 EXPORT_OF ""
set_interface_property c0 PORT_NAME_MAP ""
set_interface_property c0 CMSIS_SVD_VARIABLES ""
set_interface_property c0 SVD_ADDRESS_GROUP ""

add_interface_port c0 csi_c0_clk clk Input 1


# 
# connection point m0
# 
add_interface m0 avalon start
set_interface_property m0 addressUnits SYMBOLS
set_interface_property m0 associatedClock c0
set_interface_property m0 associatedReset c0_reset
set_interface_property m0 bitsPerSymbol 8
set_interface_property m0 burstOnBurstBoundariesOnly false
set_interface_property m0 burstcountUnits WORDS
set_interface_property m0 doStreamReads false
set_interface_property m0 doStreamWrites false
set_interface_property m0 holdTime 0
set_interface_property m0 linewrapBursts false
set_interface_property m0 maximumPendingReadTransactions 0
set_interface_property m0 maximumPendingWriteTransactions 0
set_interface_property m0 readLatency 0
set_interface_property m0 readWaitTime 1
set_interface_property m0 setupTime 0
set_interface_property m0 timingUnits Cycles
set_interface_property m0 writeWaitTime 0
set_interface_property m0 ENABLED true
set_interface_property m0 EXPORT_OF ""
set_interface_property m0 PORT_NAME_MAP ""
set_interface_property m0 CMSIS_SVD_VARIABLES ""
set_interface_property m0 SVD_ADDRESS_GROUP ""

add_interface_port m0 avm_m0_read_n read_n Output 1
add_interface_port m0 avm_m0_write_n write_n Output 1
add_interface_port m0 avm_m0_address address Output 32
add_interface_port m0 avm_m0_readdata readdata Input 32
add_interface_port m0 avm_m0_readdatavalid readdatavalid Input 1
add_interface_port m0 avm_m0_writedata writedata Output 32
add_interface_port m0 avm_m0_byteenable byteenable Output 4
add_interface_port m0 avm_m0_waitrequest waitrequest Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock c0
set_interface_property conduit_end associatedReset c0_reset
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end EnableStart export Input 1

