# TCL File Generated by Component Editor 13.1
# Tue Aug 11 13:02:19 IDT 2020
# DO NOT MODIFY


# 
# Avl2I2CBridge "Avalon To I2C Bridge" v1.0
# Inon Yagolnizer 2020.08.11.13:02:19
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module Avl2I2CBridge
# 
set_module_property DESCRIPTION ""
set_module_property NAME Avl2I2CBridge
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "CusP components"
set_module_property AUTHOR "Inon Yagolnizer"
set_module_property DISPLAY_NAME "Avalon To I2C Bridge"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Avl2I2CBridge
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
# add_fileset_file AltInitConstantPKG.vhd VHDL PATH AltInitConstantPKG.vhd
add_fileset_file Avl2I2CBridge.vhd VHDL PATH Avl2I2CBridge.vhd TOP_LEVEL_FILE
add_fileset_file ParallelToI2C.vhd VHDL PATH ParallelToI2C.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point c0_reset
# 
add_interface c0_reset reset end
set_interface_property c0_reset associatedClock c0
set_interface_property c0_reset synchronousEdges DEASSERT
set_interface_property c0_reset ENABLED true
set_interface_property c0_reset EXPORT_OF ""
set_interface_property c0_reset PORT_NAME_MAP ""
set_interface_property c0_reset CMSIS_SVD_VARIABLES ""
set_interface_property c0_reset SVD_ADDRESS_GROUP ""

add_interface_port c0_reset csi_c0_reset_n reset_n Input 1


# 
# connection point c0
# 
add_interface c0 clock end
set_interface_property c0 clockRate 0
set_interface_property c0 ENABLED true
set_interface_property c0 EXPORT_OF ""
set_interface_property c0 PORT_NAME_MAP ""
set_interface_property c0 CMSIS_SVD_VARIABLES ""
set_interface_property c0 SVD_ADDRESS_GROUP ""

add_interface_port c0 csi_c0_clk clk Input 1


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock c0
set_interface_property s0 associatedReset c0_reset
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 1
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 avs_s0_read_n read_n Input 1
add_interface_port s0 avs_s0_write_n write_n Input 1
add_interface_port s0 avs_s0_chipselect_n chipselect_n Input 1
add_interface_port s0 avs_s0_readdata readdata Output 32
add_interface_port s0 avs_s0_readdatavalid readdatavalid Output 1
add_interface_port s0 avs_s0_writedata writedata Input 32
add_interface_port s0 avs_s0_waitrequest waitrequest Output 1
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock c0
set_interface_property conduit_end associatedReset c0_reset
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end SDA export Bidir 1
add_interface_port conduit_end SCL export Output 1

